### ISSUE TITLE
Sql exception caught on [dropdown menu] 'My assessment'

### ISSUE THREAD

**Issue by ashrestha18** [JeffPerando/Slice-of-Pi#129]
After signing in with a registered account, I went to the 'User Assessment' page. I tried submitting an address that causes a SQL exception
![sqlbug](https://user-images.githubusercontent.com/56094362/165404410-b501e891-0b56-4e48-bb90-c4b89a6ec4df.JPG)

**Comment by JeffPerando** [comment]
This one was annoying, but it seems to be fixed now. Will get fixed this sprint. Thanks!
