### ISSUE TITLE
[Bug] Invalid exception caught on user info

### ISSUE THREAD

**Issue by ashrestha18** [JeffPerando/Slice-of-Pi#138]
As a logged in user, when I hit edit address button. It causes an invalid exception on Dbcontext
![invalidexception](https://user-images.githubusercontent.com/56094362/165405398-2a28a4da-04d9-456c-a70b-1af1e47f24c3.JPG)

**Comment by JeffPerando** [comment]
I believe I fixed this recently. Will reopen if we find it again.
